### ISSUE TITLE
Support CocoaPods

### ISSUE THREAD

**Issue by ZsoltMolnarMBH** [gonzalezreal/MarkdownUI#103]
Hello!
We are working on an enterprise application, which is forced to use CocoaPods.
Unfortunately this repo has no podspec file. :(

**Comment by gonzalezreal** [comment]
Hi,

Sorry, but I have no plans to support Cocoapods or maintain a pod spec. However, since Cocoapods is a centralized dependency manager, you could create a pod spec yourself and add it to their specs repository.
