### ISSUE TITLE
Crashes when rendering unfinished code block

### ISSUE THREAD

**Issue by 29decibel** [gonzalezreal/MarkdownUI#104]
Given content:
```swift
let testMarkdown = "here is some code ```"

// view code
Markdown(testMarkdown)
```
When rendering the above it would crash. Here is the crashing info:

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/97426/165399977-058da85a-c2b0-4d98-83b5-9bed2cf994c7.png">

**Comment by gonzalezreal** [comment]
Hi @29decibel,
Thanks for reporting this issue. I will fix is ASAP.

**Comment by gonzalezreal** [comment]
Hey @29decibel,

The fix for this issue will be included in the next release.

Thanks!
