### ISSUE TITLE
"UIViewRepresentables must be value types: MarkdownUI" Exception in iOS 16 beta

### ISSUE THREAD

**Issue by Terabyte1385** [gonzalezreal/MarkdownUI#108]
To make it clear, in the stable iOS 15.5 release, this issue does not occur. App built using Xcode 14 beta.

At the `@main` line in `My_Awesome_AppApp.swift`, an exception is thrown, saying `UIViewRepresentables must be value types: MarkdownUI`. I don't even know what that's supposed to mean, can anyone help?

<img width="794" alt="Screenshot 2022-06-20 at 15 49 31" src="https://user-images.githubusercontent.com/78782971/174605331-fbdbafef-7874-439c-bf9e-16177570f661.png">

Here's a demo project to demonstrate the problem:
[TestAppDemo.zip](https://github.com/gonzalezreal/MarkdownUI/files/8940706/TestAppDemo.zip)

**Comment by gonzalezreal** [comment]
Hi @Terabyte1385,
Thanks for reporting this. I will look into it before the official iOS 16 is released.

**Comment by gonzalezreal** [comment]
Hi @Terabyte1385,
The demo project you have provided is not using this library (MarkdownUI). Instead, it is using https://github.com/keitaoouchi/MarkdownView.

In any case, I ran the sample project from this library, MarkdownUIDemo on Xcode 14.0 Beta 3 and I couldn't reproduce the issue you mention.

**Comment by Terabyte1385** [comment]
Oh my days, I'm truly sorry, I haven't realised that. Thanks for investigating anyway!
