### ISSUE TITLE
Ambiguous use of 'frame'.

### ISSUE THREAD

**Issue by tskwara** [gonzalezreal/MarkdownUI#179]
Guille-

I'm running into an 'Ambiguous use of 'frame' build error.  Your View extension has frame overloads that all look right, but for some reason Xcode is having trouble disambiguating between the base initializes and yours.

-Tom

**Comment by gonzalezreal** [comment]
Thanks for the clarification. I guess I will need to rename those methods to avoid ambiguity.

**Comment by gonzalezreal** [comment]
Hey @tskwara, I believe this PR fixes the issue: #180.
Let me know otherwise and thanks for trying out the `gfm-and-swiftui-native-rendering` branch!

**Comment by gonzalezreal** [comment]
Fixed in #181, this time for good.
