### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by kernjackson** [gonzalezreal/MarkdownUI#19]
Add Package Dependency by **version** results in the following error. Setting the rules to Branch: main worked.

<img width="751" alt="Screen Shot 2020-12-30 at 7 25 34 PM" src="https://user-images.githubusercontent.com/6172851/103389766-79b08380-4ad6-11eb-8bf8-9106d0759c55.png">

**Comment by gonzalezreal** [comment]
Thanks for reporting this. A fix is on the way.

**Comment by gonzalezreal** [comment]
Should be working properly with the release 0.1.1
