### ISSUE TITLE
Disable image longpress menu

### ISSUE THREAD

**Issue by arnaud512** [gonzalezreal/MarkdownUI#24]
Hi @gonzalezreal, 
Is it possible to remove the menu when long press an image?

Thanks :) 

Example:
![IMG_305902186B08-1](https://user-images.githubusercontent.com/3939593/103491471-2437e780-4df2-11eb-94f7-414f742f8644.jpeg)

**Comment by gonzalezreal** [comment]
Hi,
This functionality will eventually be implemented in [gonzalezreal/AttributedText](https://github.com/gonzalezreal/AttributedText).

**Comment by gonzalezreal** [comment]
Hi,
This has been fixed in [MarkdownUI 1.0.0](https://github.com/gonzalezreal/MarkdownUI/releases/tag/1.0.0)
