### ISSUE TITLE
是否支持加载md文件？【Do you support loading md files?】

### ISSUE THREAD

**Issue by Jdb156158** [gonzalezreal/MarkdownUI#26]
能够支持加载显示md文件吗，Is it possible to display md files when loading

**Comment by gonzalezreal** [comment]
When you create a `Markdown` view, you need to pass a CommonMark `Document`. You can create a `Document` using a string literal, a string, or the content of a file at a specific path. [One of the examples](https://github.com/gonzalezreal/MarkdownUI/blob/main/Examples/MarkdownUIDemo/Shared/ReadMeView.swift) in the demo project shows how to load a document from a resource and display it.

**Comment by Jdb156158** [comment]
好的，非常感谢
