### ISSUE TITLE
Plans to support markdown extensions

### ISSUE THREAD

**Issue by santi-g-s** [gonzalezreal/MarkdownUI#29]
Do you have any plans to support markdown extensions such as:

Tables,
Emojis 
Etc. 

Thanks for all the great work!

**Comment by gonzalezreal** [comment]
Sorry, I have no plans to support GitHub extensions at the moment. I would consider it in the future if there is enough interest in the community.

Extension parsing should be feasible, using [GitHub's fork](https://github.com/github/cmark-gfm) of the CommonMark parser. Rendering could be more challenging, specially with tables.

**Comment by santi-g-s** [comment]
Very understandable, thank you.

**Comment by HeebeLee** [comment]
I support the idea

**Comment by ElectricS01** [comment]
Now that tables are supported could we see emoji support at some point?
