### ISSUE TITLE
 mulitiple line space is not equal, influence by paragraphSeparator

### ISSUE THREAD

**Issue by oblank** [gonzalezreal/MarkdownUI#42]
![screenshot](https://i.ibb.co/tKvNkGr/1618474119772.jpg)

just like the screenshot 

and the markedown text is:

```
#"""
        作者：[@jedz](https://www.v2ex.com/u/jedz)，节点：[#程序员](https://www.v2ex.com/go/programmer) ，31回复，发布时间：2021-04-13 18:54:26

        日经问题：笔记软件的选择。。。

        用了好多年 OneNote，不过碍于以下几个问题现在想弃坑了：

        1. 字体问题，下英文字体动不动变成 calibri，很不爽。（用了 [OneFont]( [https://lxf.me/116](https://lxf.me/116)) 基本解决问题）

        2. 对插入代码的支持很差，不支持高亮，而且有时复制出来时会有奇怪的字符，导致粘贴后不能直接运行。

        3. 如果在页面中创建了多个框，则不能自适应宽度，然后移动端上就要拖来拖去才能看。

        4. 无本地文件（ UWP 和 Mac 版）。

        然后最近试用了一周 Notion，总体感觉还不错，目前遇到两个问题比较影响体验（也可能是我不会用，求指点
"""#
```

I found the `static let paragraphSeparator = "\u{2029}"` caused this bug, if I set it to empty by `static let paragraphSeparator = ""`, it looks ok 

but loose the paragraph's  line height between

**Comment by gonzalezreal** [comment]
🤔 That doesn't make much sense, as `paragraphSeparator` is used to separate the paragraphs, not the lines inside a paragraph.

I will have a look, nevertheless. Thanks for reporting!

**Comment by oblank** [comment]
> 🤔 That doesn't make much sense, as `paragraphSeparator` is used to separate the paragraphs, not the lines inside a paragraph.
> 
> I will have a look, nevertheless. Thanks for reporting!

It's confused，and if only english words, it seems there is no bug.

Thanks

**Comment by gonzalezreal** [comment]
I did a bit of research and it is related to paragraph styles, rather than the paragraph separator. That is, if there are paragraphs in the resulting attributed strings, then you get the weird differences in line spacing. I still have no clue on how to fix this one.

**Comment by oblank** [comment]
> I did a bit of research and it is related to paragraph styles, rather than the paragraph separator. That is, if there are paragraphs in the resulting attributed strings, then you get the weird differences in line spacing. I still have no clue on how to fix this one.

get.

Thanks for your works.

**Comment by gonzalezreal** [comment]
To me, it looks like an iOS-only issue. Here is a screenshot of the Dingus example running in macOS:

![Screenshot 2021-04-16 at 09 14 39](https://user-images.githubusercontent.com/373190/114986399-3d8e0c80-9e94-11eb-9ff1-073e265b901e.png)

I see a consistent line spacing that only differs a little when the line has mixed Latin and Chinese characters, which is expected.

**Comment by oblank** [comment]
finaly, I found this [https://stackoverflow.com/questions/6367681/line-spacing-in-multi-language-layout-with-core-text](https://stackoverflow.com/questions/6367681/line-spacing-in-multi-language-layout-with-core-text)

looks like it's not a bug, but a typesetting systems problem. and after some research I 'fix' it with some codes below

```
paragraphStyle.lineSpacing  = 0.25 * font.pointSize
paragraphStyle.maximumLineHeight = font.lineHeight;
paragraphStyle.minimumLineHeight = font.lineHeight;
```

looks better.

![screenshot](https://i.ibb.co/vc1LCHP/Simulator-Screen-Shot-i-Phone-12-Pro-2021-04-16-at-16-12-00.png)

**Comment by gonzalezreal** [comment]
Yeah, that makes sense as a workaround. But the default values in the paragraph style should work properly as well.

**Comment by gonzalezreal** [comment]
Hi @oblank,
I have been testing this with MarkdownUI 1.0.0 (which comes with a new renderer), and I can't reproduce it. It displays the markdown you provided correctly in iOS 14, iOS 14.5, and iOS 15.0.

<img width="371" alt="Screenshot 2022-01-17 at 07 59 36" src="https://user-images.githubusercontent.com/373190/149722903-d566984b-5964-4256-a8d8-d15cae23660e.png">
