### ISSUE TITLE
Example on blockQuoteAttributes usage

### ISSUE THREAD

**Issue by morad** [gonzalezreal/MarkdownUI#43]
Hello,

Can I get an example/tip on how to utilize blockQuoteAttributes func in my SwiftUI. Basically, I am trying to change the background and some font attributes.

Thanks,

Morad

**Comment by oblank** [comment]
conform  `MarkdownStyle` protocol

```
func blockQuoteAttributes(_ attributes: inout [NSAttributedString.Key: Any])
```

this function may help you.

**Comment by morad** [comment]
Can you please provide an example on how to call blockQuoteAttributes or paragraphAttributes. I've tried the following, but no luck.

I am getting this error: 

"Cannot find 'paragraphAttributes' in scope"

```
Markdown(
                            #"""
                            \#(post.shortSummary)
                            """#
                        ).markdownStyle(
                            paragraphAttributes(paragraphStyle.lineSpacing = 2)
                        )
```

Thanks!
