### ISSUE TITLE
Are local images supported?

### ISSUE THREAD

**Issue by codebeauty** [gonzalezreal/MarkdownUI#46]
Great library. Before I want to dive deeper into it, one question. Do you support local images? I see your example with an remote image. Is it possible to link a local image? Maybe from the asset bundle?

Thank you for your work. 👍

**Comment by gonzalezreal** [comment]
**MarkdownUI** can render local images, provided that they can be located inside the bundle using a URL. This means that the image cannot be inside an asset catalog, and that you will need to set the markdown base URL to the bundle's resource URL. For example:

<img width="272" alt="Screenshot 2021-04-25 at 17 14 09" src="https://user-images.githubusercontent.com/373190/115998873-b1918880-a5e9-11eb-82df-0af1619c33b3.png">


```swift
Markdown(
    #"""
    This is a local image:

    ![Dog](dog.jpg)
    """#
)
.markdownBaseURL(Bundle.main.resourceURL)
```

**Comment by markusmoenig** [comment]
@gonzalezreal Also from my side thanks for MarkdownUI.

But could we not somehow define a sub folder of the base url for the images ? I want todo my dynamic help system with MarkdownUI and putting like 20-30 images into the main resource folder would mess up my project big time ... .

**Comment by codebeauty** [comment]
Thank you for the clarification and keep up the great work 🧡
