### ISSUE TITLE
html tag render image size too large

### ISSUE THREAD

**Issue by jiangdi0924** [gonzalezreal/MarkdownUI#53]
This pkg is very helpful for me , thank you !
A bit issue when i render a html tag document ,  how can i fix it?
`document =  #"""
        <h2></2>
        <img src="https://octodex.github.com/images/stormtroopocat.jpg" alt=""/>
        """#`

![image](https://user-images.githubusercontent.com/21988177/121982504-30bd6480-cdc2-11eb-94cc-4cb7af4a0867.png)

**Comment by kevoniori** [comment]
You could try the following code below and adjust the parameters to your liking.
<style> img {border-radius: 30px; width: 100% ; height: 300 ; margin-left: auto ; margin-right: auto }  </style>

**Comment by kevoniori** [comment]
How did you get to render the markdown using html? Mine just spits out the plain text.

**Comment by jiangdi0924** [comment]
> How did you get to render the markdown using html? Mine just spits out the plain text.

try this : 
```
import MarkdownUI

let doc = #"""
 <h2>test</h2> <p>balablalalalala</p>
"""#
Markdown(Document((doc))

```
**Note**: i find  if the top level html code without _<h*>_ tag , then the html will not render completely.

**Comment by kevoniori** [comment]
Tried it with your example and it worked, but I tried it with a wordpress rest api and it didnt work

**Comment by gonzalezreal** [comment]
HTML rendering is *very limited* now. I am working on improving it for version 1.0. The goal is to cover the HTML tags equivalent to markdown, both in blocks and inlines. However, a rule of thumb is to use markdown syntax when possible.
