### ISSUE TITLE
Images not showing up when using Markdown

### ISSUE THREAD

**Issue by kevoniori** [gonzalezreal/MarkdownUI#57]
I'm parsing markdown content from the Contentful CMS into my app. The texts and links are all formatted and displayed as they should (e.g. lists, bold, links, italics, etc.), however, when I insert images, they won't load. The image URL structure is the same as is documented to use with Markdown UI but they won't come up. It will come up in the preview editor from Contentful but inside my app nothing shows. Is this something to do with markdown UI or is there another piece of functionality I need to call from the Module?

**Comment by kevoniori** [comment]
Attached are two examples. One of how it looks when the app launches and the other from the Contentful backend.
![Screen Shot 2021-07-08 at 2 15 30 PM](https://user-images.githubusercontent.com/86158992/124978180-0e042180-dff7-11eb-8689-a80624cb6b66.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-08 at 14 15 13](https://user-images.githubusercontent.com/86158992/124978183-0f354e80-dff7-11eb-93bd-8f18bee273c6.png)

**Comment by gonzalezreal** [comment]
Hi,
It looks like the image URLs in your example are relative URLs. Therefore, you must use the `markdownBaseURL` modifier to set a base URL for the images, as demonstrated in the companion demo app:

https://github.com/gonzalezreal/MarkdownUI/blob/890d6341bd5c487df0b1f7dae04173fb9963f565/Examples/MarkdownUIDemo/Shared/ReadMeView.swift#L18

**Comment by kevoniori** [comment]
This helped so alot. Images are showing up now, thanks much @gonzalezreal
