### ISSUE TITLE
open image when tap on it 

### ISSUE THREAD

**Issue by oblank** [gonzalezreal/MarkdownUI#58]
is there some way to open image when tap on it, like LightBox's style？

**Comment by gonzalezreal** [comment]
Hello,
This requirement is out of the scope of this package. You can achieve something close to it by creating an image link in markdown:
```markdown
[![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)](https://octodex.github.com/images/yaktocat.png)
```

Furthermore, you could use your own URL scheme for the links and open the images in a native way. You can find more info about handling deep links in SwiftUI in [this post](https://www.donnywals.com/handling-deeplinks-in-ios-14-with-onopenurl/).
