### ISSUE TITLE
Open in-app browser

### ISSUE THREAD

**Issue by shahla00** [gonzalezreal/MarkdownUI#60]
It will be nice if there is a way to give custom actions to links instead of always opening in Safari. For our use, we want to open SFSafariViewController but MarkdownUI does not have that ability!

I implemented it through custom urls, but it is an ugly hack and I shouldn't have to do that.

**Comment by gonzalezreal** [comment]
Duplicate of #52

**Comment by gonzalezreal** [comment]
Hi @shahla00,
This has been already discussed in #52. I will reopen #52 and continue the discussion there.
Thanks!
