### ISSUE TITLE
Support for cmark-gfm

### ISSUE THREAD

**Issue by yoshimaru46** [gonzalezreal/MarkdownUI#61]
Is there any plan to support github flavored markdown spec?
refs: https://github.com/github/cmark-gfm

**Comment by gonzalezreal** [comment]
Duplicate of #29

**Comment by gonzalezreal** [comment]
Hi @yoshimaru46,
This has already been discussed [here](https://github.com/gonzalezreal/MarkdownUI/issues/29#issuecomment-760010908).
