### ISSUE TITLE
break combine-schedulers dependency

### ISSUE THREAD

**Issue by heltena** [gonzalezreal/MarkdownUI#62]
Hello,

the package "combine-schedulers" just release a new version 0.5.2 that breaks your MarkdownUI package. In your dependencies it appears:

        .package(url: "https://github.com/pointfreeco/combine-schedulers", from: "0.1.2"),

It will be great to update the "from:" to the version you think is the good one and release a new version.

Thanks!

**Comment by gonzalezreal** [comment]
Thanks for reporting this. It should be fixed in: https://github.com/gonzalezreal/MarkdownUI/releases/tag/0.5.2
