### ISSUE TITLE
latest version of combine-schedulers is incompatible w/NetworkImag

### ISSUE THREAD

**Issue by jfrodden** [gonzalezreal/MarkdownUI#64]
this package requires https://github.com/gonzalezreal/NetworkImage, which requires https://github.com/pointfreeco/combine-schedulers, which just moved to version 0.5.2 which requires iOS13, but these two packages export support for iOS11, this breaks our app when Xcode auto-updates our dependency chain.

**Comment by gonzalezreal** [comment]
duplicates #19 #62

**Comment by gonzalezreal** [comment]
This should be fixed in https://github.com/gonzalezreal/MarkdownUI/releases/tag/0.5.2
