### ISSUE TITLE
Markdown appears in SwiftUI preview but not in simulator or on device

### ISSUE THREAD

**Issue by antonjazz** [gonzalezreal/MarkdownUI#67]
This is a strange issue that started occurring to me recently.
I made a test app to demonstrate it at [https://github.com/antonjazz/MarkdownTest](https://github.com/antonjazz/MarkdownTest)
If you look at the `MainView.swift` file along with its SwiftUI Preview, you'll see the markdown renders fine.
But in the Simulator it never appears at all.
I'm using Xcode 12.5.1.

Any ideas?

**Comment by jiangdi0924** [comment]
+1

**Comment by john-ibsa** [comment]
+1

**Comment by erdincIceMobile** [comment]
+1

**Comment by erdincIceMobile** [comment]
+1

**Comment by gonzalezreal** [comment]
Could this be related to #78?

**Comment by antonjazz** [comment]
> Could this be related to #78?

Unfortunately it doesn't seem so. At least, the [test app](https://github.com/antonjazz/MarkdownTest) I link to above that demonstrates it doesn't present any sheets. Here's [its main view](https://github.com/antonjazz/MarkdownTest/blob/main/MarkdownTest/MainView.swift).

**Comment by gonzalezreal** [comment]
I can't run the previews on the project you provided due to some misconfiguration of the preview content. Could you please try to reproduce the issue using the `release-1.0` branch?

**Comment by gonzalezreal** [comment]
@antonjazz, Could you please check if this is still reproducing in `MarkdownUI 1.0.0`?

**Comment by antonjazz** [comment]
Fixed it! 🎯👍
