### ISSUE TITLE
Markdown not displaying in Xcode 13

### ISSUE THREAD

**Issue by kevoniori** [gonzalezreal/MarkdownUI#77]
Ever since I updated to Xcode 13.1 and started working with iOS 15, the markdown parsing doesn't seem to be working. It's just a blank screen now. I'm using the latest version of Markdown UI as well. It used to work before but now it has just...stopped

**Comment by gonzalezreal** [comment]
I haven't seen any issues with Xcode 13.1 and iOS 15.0. Please, provide a test project that reproduces the problem. Otherwise, I can't help you.

**Comment by danielbuechele** [comment]
I do have the same issue. I haven't yet been able to reproduce it in a standalone project, though.

**Comment by gonzalezreal** [comment]
Hi,
I fixed iOS 15 view updating issues (#78) in #83. Notice that this fix is in the `release-1.0` branch, which is still a work in progress and contains other breaking changes.
