### ISSUE TITLE
Markdown text disappearing after presenting a sheet

### ISSUE THREAD

**Issue by helloniklas** [gonzalezreal/MarkdownUI#78]
So I have this app with a rather elaborate view hierarchy. For some reason when I present a sheet on top of the Markdown text then dismiss it the markdown text disappears but everything is else is still there. 

I've tried to present a sheet in a vanilla standalone project and it works fine there. So not sure exactly what triggers this behaviour in my project. But all other UI elements works fine, it's only the markdown view that disappears.

Any idea why this could happen? Something with the states of the view not re-rendering somehow?

**Comment by mokkun** [comment]
Have a similar issue, but when displaying a context menu for a list item that has markdown.

**Comment by heltena** [comment]
I had a similar issue. In my case, everything works on iOS 14, but Markdown disappears o iOS 15. I could isolate the error in a simple example:

https://github.com/heltena/MarkdownTest

To reproduce the error:
- Run on a iOS 15 device (simulator also works)
- Click on "Show Challenge"
- You will see the markdown and a horrible red rectangle.
- Tap and drag your finger on that horrible red rectangle.
- The Markdown should disappear.

Best!

**Comment by helloniklas** [comment]
I'm seeing the issue in both iOS14.5 and iOS15...

**Comment by heltena** [comment]
Sorry, maybe I should have opened another ticket instead of using yours. It looks close similar. Could you try my pull request in your code?

**Comment by helloniklas** [comment]
Yeah it’s probably related. Will try it when I’ll get back to a computer.

**Comment by gonzalezreal** [comment]
I will have a look at this as soon as I can. Thanks for reporting it.

**Comment by gonzalezreal** [comment]
Hi all,

I fixed this issue in the `release-1.0` branch. Notice this branch is still a work in progress and contains other breaking changes I am making in preparation for the upcoming 1.0 release.

@heltena, thanks for providing a test project to reproduce the issue. That helped a lot.

**Comment by helloniklas** [comment]
I can confirm his solves my issue as well. Many thanks.
