### ISSUE TITLE
Cannot Customize MarkdownStyle details

### ISSUE THREAD

**Issue by kikimaxs** [gonzalezreal/MarkdownUI#91]
I have example string markdown :

`"\n#### Paket yang dipilih\n### **Paket Mobile** \n\n#### Waktu berakhir paket\n### Kamis, 11 Februari 2021 02:10 WIB \n\n**Keuntungan yang Anda dapatkan jika berlangganan:**\n- Jelajahi dan nikmati konten Mola tanpa batasan\n- Menonton tanpa Iklan\n- Dapat menonton di Aplikasi Mobile atau Browser PC atau Laptop Anda\n\nSegera perpanjang masa paket Anda agar dapat menikmati keuntungannya. "` .

I just follow your reference but  i can't make as expected,
example code :

```
                Markdown(inboxDetailsVm.inboxDetailsGetVM?.attribute.template.lang.first?.message ?? "")
                            .markdownStyle(
                                MarkdownStyle(
                                    font: .custom("OpenSans-Light", size: 14),
                                    foregroundColor: .white,
                                    measurements: .init(
                                        codeFontScale: 0.8,
                                        headingSpacing: 0.5
                                    )
                                    
                                )
                            )
                            .multilineTextAlignment(.leading)  
```

there is my reality like the following picture:

<img width="313" alt="Screen Shot 2022-02-11 at 11 16 55 AM" src="https://user-images.githubusercontent.com/41480877/153536882-0083cded-d87a-4459-8f7f-2deee5f0911e.png">

and the expectations are like the following picture:

<img width="358" alt="Screen Shot 2022-02-09 at 12 18 53 PM" src="https://user-images.githubusercontent.com/41480877/153126719-e03c7a23-9c55-4a70-8e76-bd9f16f3546a.png">

how to use markdownStyle in detail ?
but i want custom style color and `fontsize`,`fontname`,`linespacing`,`padding`,`width`,`height` by part `H1,H2,H3,H4,H5,H6` and then `blockquote`, and `list`, etc.
I think that the reference you have attached is incomplete in the explanation of the example,
I'm so confused and hope you can answer my question and give me a solution.
Thank you :)

**Comment by kikimaxs** [comment]
Hi @gonzalezreal,
I have edited my previous comment so you could understood my current issue.

**Comment by gonzalezreal** [comment]
Hi,
At the moment, MarkdownUI doesn't support styling blocks or inlines. I will consider adding more styling options in a future release. In the meantime, have a look at the inline documentation in the following files to know what you can style now:

- [Sources/MarkdownUI/Style/MarkdownStyle.swift](https://github.com/gonzalezreal/MarkdownUI/blob/4c164300337a35d002188a83a878346819b203c0/Sources/MarkdownUI/Style/MarkdownStyle.swift)
- [Sources/MarkdownUI/Style/Measurements.swift](https://github.com/gonzalezreal/MarkdownUI/blob/4c164300337a35d002188a83a878346819b203c0/Sources/MarkdownUI/Style/Measurements.swift)
- [Sources/MarkdownUI/Style/HeadingScales.swift](https://github.com/gonzalezreal/MarkdownUI/blob/4c164300337a35d002188a83a878346819b203c0/Sources/MarkdownUI/Style/HeadingScales.swift)
