### ISSUE TITLE
horizontal line elements `***` don't render correctly when centred

### ISSUE THREAD

**Issue by bartreardon** [gonzalezreal/MarkdownUI#99]
when rendering a markdown document, if I apply a `.multilineTextAlignment(.center)` modifier, the text will center just fine but but horizontal  lines `***` _start_ at the center point and are not centered.

example centred:
![image](https://user-images.githubusercontent.com/3598965/159818267-31b1ef6b-1d9f-442c-a89d-f07c08ff7423.png)

example left justified:
![image](https://user-images.githubusercontent.com/3598965/159818319-2b66f48c-3f88-40a0-b0cb-e55c92f09aeb.png)

**Comment by gonzalezreal** [comment]
I will look into this. Thanks for reporting it.

**Comment by gonzalezreal** [comment]
Hey @bartreardon,

The fix for this issue will be included in the next release.

Thanks!
